// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vtrod/veecomm-api/ent/cart"
	"github.com/vtrod/veecomm-api/ent/cartitem"
	"github.com/vtrod/veecomm-api/ent/predicate"
	"github.com/vtrod/veecomm-api/ent/user"
)

// CartUpdate is the builder for updating Cart entities.
type CartUpdate struct {
	config
	hooks    []Hook
	mutation *CartMutation
}

// Where appends a list predicates to the CartUpdate builder.
func (cu *CartUpdate) Where(ps ...predicate.Cart) *CartUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *CartUpdate) SetUserID(s string) *CartUpdate {
	cu.mutation.SetUserID(s)
	return cu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cu *CartUpdate) SetNillableUserID(s *string) *CartUpdate {
	if s != nil {
		cu.SetUserID(*s)
	}
	return cu
}

// ClearUserID clears the value of the "user_id" field.
func (cu *CartUpdate) ClearUserID() *CartUpdate {
	cu.mutation.ClearUserID()
	return cu
}

// SetSubtotal sets the "subtotal" field.
func (cu *CartUpdate) SetSubtotal(f float64) *CartUpdate {
	cu.mutation.ResetSubtotal()
	cu.mutation.SetSubtotal(f)
	return cu
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (cu *CartUpdate) SetNillableSubtotal(f *float64) *CartUpdate {
	if f != nil {
		cu.SetSubtotal(*f)
	}
	return cu
}

// AddSubtotal adds f to the "subtotal" field.
func (cu *CartUpdate) AddSubtotal(f float64) *CartUpdate {
	cu.mutation.AddSubtotal(f)
	return cu
}

// SetShipping sets the "shipping" field.
func (cu *CartUpdate) SetShipping(f float64) *CartUpdate {
	cu.mutation.ResetShipping()
	cu.mutation.SetShipping(f)
	return cu
}

// SetNillableShipping sets the "shipping" field if the given value is not nil.
func (cu *CartUpdate) SetNillableShipping(f *float64) *CartUpdate {
	if f != nil {
		cu.SetShipping(*f)
	}
	return cu
}

// AddShipping adds f to the "shipping" field.
func (cu *CartUpdate) AddShipping(f float64) *CartUpdate {
	cu.mutation.AddShipping(f)
	return cu
}

// ClearShipping clears the value of the "shipping" field.
func (cu *CartUpdate) ClearShipping() *CartUpdate {
	cu.mutation.ClearShipping()
	return cu
}

// SetDiscount sets the "discount" field.
func (cu *CartUpdate) SetDiscount(f float64) *CartUpdate {
	cu.mutation.ResetDiscount()
	cu.mutation.SetDiscount(f)
	return cu
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (cu *CartUpdate) SetNillableDiscount(f *float64) *CartUpdate {
	if f != nil {
		cu.SetDiscount(*f)
	}
	return cu
}

// AddDiscount adds f to the "discount" field.
func (cu *CartUpdate) AddDiscount(f float64) *CartUpdate {
	cu.mutation.AddDiscount(f)
	return cu
}

// SetTotal sets the "total" field.
func (cu *CartUpdate) SetTotal(f float64) *CartUpdate {
	cu.mutation.ResetTotal()
	cu.mutation.SetTotal(f)
	return cu
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (cu *CartUpdate) SetNillableTotal(f *float64) *CartUpdate {
	if f != nil {
		cu.SetTotal(*f)
	}
	return cu
}

// AddTotal adds f to the "total" field.
func (cu *CartUpdate) AddTotal(f float64) *CartUpdate {
	cu.mutation.AddTotal(f)
	return cu
}

// SetAppliedCoupon sets the "applied_coupon" field.
func (cu *CartUpdate) SetAppliedCoupon(b bool) *CartUpdate {
	cu.mutation.SetAppliedCoupon(b)
	return cu
}

// SetNillableAppliedCoupon sets the "applied_coupon" field if the given value is not nil.
func (cu *CartUpdate) SetNillableAppliedCoupon(b *bool) *CartUpdate {
	if b != nil {
		cu.SetAppliedCoupon(*b)
	}
	return cu
}

// SetCouponCode sets the "coupon_code" field.
func (cu *CartUpdate) SetCouponCode(s string) *CartUpdate {
	cu.mutation.SetCouponCode(s)
	return cu
}

// SetNillableCouponCode sets the "coupon_code" field if the given value is not nil.
func (cu *CartUpdate) SetNillableCouponCode(s *string) *CartUpdate {
	if s != nil {
		cu.SetCouponCode(*s)
	}
	return cu
}

// ClearCouponCode clears the value of the "coupon_code" field.
func (cu *CartUpdate) ClearCouponCode() *CartUpdate {
	cu.mutation.ClearCouponCode()
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CartUpdate) SetCreatedAt(t time.Time) *CartUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CartUpdate) SetNillableCreatedAt(t *time.Time) *CartUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CartUpdate) SetUpdatedAt(t time.Time) *CartUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CartUpdate) SetUser(u *User) *CartUpdate {
	return cu.SetUserID(u.ID)
}

// AddCartItemIDs adds the "cart_items" edge to the CartItem entity by IDs.
func (cu *CartUpdate) AddCartItemIDs(ids ...string) *CartUpdate {
	cu.mutation.AddCartItemIDs(ids...)
	return cu
}

// AddCartItems adds the "cart_items" edges to the CartItem entity.
func (cu *CartUpdate) AddCartItems(c ...*CartItem) *CartUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddCartItemIDs(ids...)
}

// Mutation returns the CartMutation object of the builder.
func (cu *CartUpdate) Mutation() *CartMutation {
	return cu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CartUpdate) ClearUser() *CartUpdate {
	cu.mutation.ClearUser()
	return cu
}

// ClearCartItems clears all "cart_items" edges to the CartItem entity.
func (cu *CartUpdate) ClearCartItems() *CartUpdate {
	cu.mutation.ClearCartItems()
	return cu
}

// RemoveCartItemIDs removes the "cart_items" edge to CartItem entities by IDs.
func (cu *CartUpdate) RemoveCartItemIDs(ids ...string) *CartUpdate {
	cu.mutation.RemoveCartItemIDs(ids...)
	return cu
}

// RemoveCartItems removes "cart_items" edges to CartItem entities.
func (cu *CartUpdate) RemoveCartItems(c ...*CartItem) *CartUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveCartItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CartUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CartUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CartUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CartUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CartUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

func (cu *CartUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Subtotal(); ok {
		_spec.SetField(cart.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedSubtotal(); ok {
		_spec.AddField(cart.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Shipping(); ok {
		_spec.SetField(cart.FieldShipping, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedShipping(); ok {
		_spec.AddField(cart.FieldShipping, field.TypeFloat64, value)
	}
	if cu.mutation.ShippingCleared() {
		_spec.ClearField(cart.FieldShipping, field.TypeFloat64)
	}
	if value, ok := cu.mutation.Discount(); ok {
		_spec.SetField(cart.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedDiscount(); ok {
		_spec.AddField(cart.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Total(); ok {
		_spec.SetField(cart.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedTotal(); ok {
		_spec.AddField(cart.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AppliedCoupon(); ok {
		_spec.SetField(cart.FieldAppliedCoupon, field.TypeBool, value)
	}
	if value, ok := cu.mutation.CouponCode(); ok {
		_spec.SetField(cart.FieldCouponCode, field.TypeString, value)
	}
	if cu.mutation.CouponCodeCleared() {
		_spec.ClearField(cart.FieldCouponCode, field.TypeString)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cart.UserTable,
			Columns: []string{cart.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cart.UserTable,
			Columns: []string{cart.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.CartItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedCartItemsIDs(); len(nodes) > 0 && !cu.mutation.CartItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CartItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CartUpdateOne is the builder for updating a single Cart entity.
type CartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartMutation
}

// SetUserID sets the "user_id" field.
func (cuo *CartUpdateOne) SetUserID(s string) *CartUpdateOne {
	cuo.mutation.SetUserID(s)
	return cuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableUserID(s *string) *CartUpdateOne {
	if s != nil {
		cuo.SetUserID(*s)
	}
	return cuo
}

// ClearUserID clears the value of the "user_id" field.
func (cuo *CartUpdateOne) ClearUserID() *CartUpdateOne {
	cuo.mutation.ClearUserID()
	return cuo
}

// SetSubtotal sets the "subtotal" field.
func (cuo *CartUpdateOne) SetSubtotal(f float64) *CartUpdateOne {
	cuo.mutation.ResetSubtotal()
	cuo.mutation.SetSubtotal(f)
	return cuo
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableSubtotal(f *float64) *CartUpdateOne {
	if f != nil {
		cuo.SetSubtotal(*f)
	}
	return cuo
}

// AddSubtotal adds f to the "subtotal" field.
func (cuo *CartUpdateOne) AddSubtotal(f float64) *CartUpdateOne {
	cuo.mutation.AddSubtotal(f)
	return cuo
}

// SetShipping sets the "shipping" field.
func (cuo *CartUpdateOne) SetShipping(f float64) *CartUpdateOne {
	cuo.mutation.ResetShipping()
	cuo.mutation.SetShipping(f)
	return cuo
}

// SetNillableShipping sets the "shipping" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableShipping(f *float64) *CartUpdateOne {
	if f != nil {
		cuo.SetShipping(*f)
	}
	return cuo
}

// AddShipping adds f to the "shipping" field.
func (cuo *CartUpdateOne) AddShipping(f float64) *CartUpdateOne {
	cuo.mutation.AddShipping(f)
	return cuo
}

// ClearShipping clears the value of the "shipping" field.
func (cuo *CartUpdateOne) ClearShipping() *CartUpdateOne {
	cuo.mutation.ClearShipping()
	return cuo
}

// SetDiscount sets the "discount" field.
func (cuo *CartUpdateOne) SetDiscount(f float64) *CartUpdateOne {
	cuo.mutation.ResetDiscount()
	cuo.mutation.SetDiscount(f)
	return cuo
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableDiscount(f *float64) *CartUpdateOne {
	if f != nil {
		cuo.SetDiscount(*f)
	}
	return cuo
}

// AddDiscount adds f to the "discount" field.
func (cuo *CartUpdateOne) AddDiscount(f float64) *CartUpdateOne {
	cuo.mutation.AddDiscount(f)
	return cuo
}

// SetTotal sets the "total" field.
func (cuo *CartUpdateOne) SetTotal(f float64) *CartUpdateOne {
	cuo.mutation.ResetTotal()
	cuo.mutation.SetTotal(f)
	return cuo
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableTotal(f *float64) *CartUpdateOne {
	if f != nil {
		cuo.SetTotal(*f)
	}
	return cuo
}

// AddTotal adds f to the "total" field.
func (cuo *CartUpdateOne) AddTotal(f float64) *CartUpdateOne {
	cuo.mutation.AddTotal(f)
	return cuo
}

// SetAppliedCoupon sets the "applied_coupon" field.
func (cuo *CartUpdateOne) SetAppliedCoupon(b bool) *CartUpdateOne {
	cuo.mutation.SetAppliedCoupon(b)
	return cuo
}

// SetNillableAppliedCoupon sets the "applied_coupon" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableAppliedCoupon(b *bool) *CartUpdateOne {
	if b != nil {
		cuo.SetAppliedCoupon(*b)
	}
	return cuo
}

// SetCouponCode sets the "coupon_code" field.
func (cuo *CartUpdateOne) SetCouponCode(s string) *CartUpdateOne {
	cuo.mutation.SetCouponCode(s)
	return cuo
}

// SetNillableCouponCode sets the "coupon_code" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableCouponCode(s *string) *CartUpdateOne {
	if s != nil {
		cuo.SetCouponCode(*s)
	}
	return cuo
}

// ClearCouponCode clears the value of the "coupon_code" field.
func (cuo *CartUpdateOne) ClearCouponCode() *CartUpdateOne {
	cuo.mutation.ClearCouponCode()
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CartUpdateOne) SetCreatedAt(t time.Time) *CartUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableCreatedAt(t *time.Time) *CartUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CartUpdateOne) SetUpdatedAt(t time.Time) *CartUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CartUpdateOne) SetUser(u *User) *CartUpdateOne {
	return cuo.SetUserID(u.ID)
}

// AddCartItemIDs adds the "cart_items" edge to the CartItem entity by IDs.
func (cuo *CartUpdateOne) AddCartItemIDs(ids ...string) *CartUpdateOne {
	cuo.mutation.AddCartItemIDs(ids...)
	return cuo
}

// AddCartItems adds the "cart_items" edges to the CartItem entity.
func (cuo *CartUpdateOne) AddCartItems(c ...*CartItem) *CartUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddCartItemIDs(ids...)
}

// Mutation returns the CartMutation object of the builder.
func (cuo *CartUpdateOne) Mutation() *CartMutation {
	return cuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CartUpdateOne) ClearUser() *CartUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// ClearCartItems clears all "cart_items" edges to the CartItem entity.
func (cuo *CartUpdateOne) ClearCartItems() *CartUpdateOne {
	cuo.mutation.ClearCartItems()
	return cuo
}

// RemoveCartItemIDs removes the "cart_items" edge to CartItem entities by IDs.
func (cuo *CartUpdateOne) RemoveCartItemIDs(ids ...string) *CartUpdateOne {
	cuo.mutation.RemoveCartItemIDs(ids...)
	return cuo
}

// RemoveCartItems removes "cart_items" edges to CartItem entities.
func (cuo *CartUpdateOne) RemoveCartItems(c ...*CartItem) *CartUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveCartItemIDs(ids...)
}

// Where appends a list predicates to the CartUpdate builder.
func (cuo *CartUpdateOne) Where(ps ...predicate.Cart) *CartUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CartUpdateOne) Select(field string, fields ...string) *CartUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Cart entity.
func (cuo *CartUpdateOne) Save(ctx context.Context) (*Cart, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CartUpdateOne) SaveX(ctx context.Context) *Cart {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CartUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CartUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CartUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

func (cuo *CartUpdateOne) sqlSave(ctx context.Context) (_node *Cart, err error) {
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cart.FieldID)
		for _, f := range fields {
			if !cart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Subtotal(); ok {
		_spec.SetField(cart.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedSubtotal(); ok {
		_spec.AddField(cart.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Shipping(); ok {
		_spec.SetField(cart.FieldShipping, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedShipping(); ok {
		_spec.AddField(cart.FieldShipping, field.TypeFloat64, value)
	}
	if cuo.mutation.ShippingCleared() {
		_spec.ClearField(cart.FieldShipping, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.Discount(); ok {
		_spec.SetField(cart.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedDiscount(); ok {
		_spec.AddField(cart.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Total(); ok {
		_spec.SetField(cart.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedTotal(); ok {
		_spec.AddField(cart.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AppliedCoupon(); ok {
		_spec.SetField(cart.FieldAppliedCoupon, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.CouponCode(); ok {
		_spec.SetField(cart.FieldCouponCode, field.TypeString, value)
	}
	if cuo.mutation.CouponCodeCleared() {
		_spec.ClearField(cart.FieldCouponCode, field.TypeString)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cart.UserTable,
			Columns: []string{cart.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cart.UserTable,
			Columns: []string{cart.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.CartItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedCartItemsIDs(); len(nodes) > 0 && !cuo.mutation.CartItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CartItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartItemsTable,
			Columns: []string{cart.CartItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cart{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
