// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vtrod/veecomm-api/ent/cart"
	"github.com/vtrod/veecomm-api/ent/cartitem"
	"github.com/vtrod/veecomm-api/ent/predicate"
	"github.com/vtrod/veecomm-api/ent/product"
)

// CartItemUpdate is the builder for updating CartItem entities.
type CartItemUpdate struct {
	config
	hooks    []Hook
	mutation *CartItemMutation
}

// Where appends a list predicates to the CartItemUpdate builder.
func (ciu *CartItemUpdate) Where(ps ...predicate.CartItem) *CartItemUpdate {
	ciu.mutation.Where(ps...)
	return ciu
}

// SetCartID sets the "cart_id" field.
func (ciu *CartItemUpdate) SetCartID(s string) *CartItemUpdate {
	ciu.mutation.SetCartID(s)
	return ciu
}

// SetNillableCartID sets the "cart_id" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableCartID(s *string) *CartItemUpdate {
	if s != nil {
		ciu.SetCartID(*s)
	}
	return ciu
}

// ClearCartID clears the value of the "cart_id" field.
func (ciu *CartItemUpdate) ClearCartID() *CartItemUpdate {
	ciu.mutation.ClearCartID()
	return ciu
}

// SetProductID sets the "product_id" field.
func (ciu *CartItemUpdate) SetProductID(s string) *CartItemUpdate {
	ciu.mutation.SetProductID(s)
	return ciu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableProductID(s *string) *CartItemUpdate {
	if s != nil {
		ciu.SetProductID(*s)
	}
	return ciu
}

// ClearProductID clears the value of the "product_id" field.
func (ciu *CartItemUpdate) ClearProductID() *CartItemUpdate {
	ciu.mutation.ClearProductID()
	return ciu
}

// SetName sets the "name" field.
func (ciu *CartItemUpdate) SetName(s string) *CartItemUpdate {
	ciu.mutation.SetName(s)
	return ciu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableName(s *string) *CartItemUpdate {
	if s != nil {
		ciu.SetName(*s)
	}
	return ciu
}

// SetPrice sets the "price" field.
func (ciu *CartItemUpdate) SetPrice(f float64) *CartItemUpdate {
	ciu.mutation.ResetPrice()
	ciu.mutation.SetPrice(f)
	return ciu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillablePrice(f *float64) *CartItemUpdate {
	if f != nil {
		ciu.SetPrice(*f)
	}
	return ciu
}

// AddPrice adds f to the "price" field.
func (ciu *CartItemUpdate) AddPrice(f float64) *CartItemUpdate {
	ciu.mutation.AddPrice(f)
	return ciu
}

// SetImage sets the "image" field.
func (ciu *CartItemUpdate) SetImage(s string) *CartItemUpdate {
	ciu.mutation.SetImage(s)
	return ciu
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableImage(s *string) *CartItemUpdate {
	if s != nil {
		ciu.SetImage(*s)
	}
	return ciu
}

// SetQuantity sets the "quantity" field.
func (ciu *CartItemUpdate) SetQuantity(i int) *CartItemUpdate {
	ciu.mutation.ResetQuantity()
	ciu.mutation.SetQuantity(i)
	return ciu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableQuantity(i *int) *CartItemUpdate {
	if i != nil {
		ciu.SetQuantity(*i)
	}
	return ciu
}

// AddQuantity adds i to the "quantity" field.
func (ciu *CartItemUpdate) AddQuantity(i int) *CartItemUpdate {
	ciu.mutation.AddQuantity(i)
	return ciu
}

// SetCreatedAt sets the "created_at" field.
func (ciu *CartItemUpdate) SetCreatedAt(t time.Time) *CartItemUpdate {
	ciu.mutation.SetCreatedAt(t)
	return ciu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ciu *CartItemUpdate) SetNillableCreatedAt(t *time.Time) *CartItemUpdate {
	if t != nil {
		ciu.SetCreatedAt(*t)
	}
	return ciu
}

// SetUpdatedAt sets the "updated_at" field.
func (ciu *CartItemUpdate) SetUpdatedAt(t time.Time) *CartItemUpdate {
	ciu.mutation.SetUpdatedAt(t)
	return ciu
}

// SetCart sets the "cart" edge to the Cart entity.
func (ciu *CartItemUpdate) SetCart(c *Cart) *CartItemUpdate {
	return ciu.SetCartID(c.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (ciu *CartItemUpdate) SetProduct(p *Product) *CartItemUpdate {
	return ciu.SetProductID(p.ID)
}

// Mutation returns the CartItemMutation object of the builder.
func (ciu *CartItemUpdate) Mutation() *CartItemMutation {
	return ciu.mutation
}

// ClearCart clears the "cart" edge to the Cart entity.
func (ciu *CartItemUpdate) ClearCart() *CartItemUpdate {
	ciu.mutation.ClearCart()
	return ciu
}

// ClearProduct clears the "product" edge to the Product entity.
func (ciu *CartItemUpdate) ClearProduct() *CartItemUpdate {
	ciu.mutation.ClearProduct()
	return ciu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ciu *CartItemUpdate) Save(ctx context.Context) (int, error) {
	ciu.defaults()
	return withHooks(ctx, ciu.sqlSave, ciu.mutation, ciu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ciu *CartItemUpdate) SaveX(ctx context.Context) int {
	affected, err := ciu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ciu *CartItemUpdate) Exec(ctx context.Context) error {
	_, err := ciu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ciu *CartItemUpdate) ExecX(ctx context.Context) {
	if err := ciu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ciu *CartItemUpdate) defaults() {
	if _, ok := ciu.mutation.UpdatedAt(); !ok {
		v := cartitem.UpdateDefaultUpdatedAt()
		ciu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ciu *CartItemUpdate) check() error {
	if v, ok := ciu.mutation.Name(); ok {
		if err := cartitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CartItem.name": %w`, err)}
		}
	}
	if v, ok := ciu.mutation.Price(); ok {
		if err := cartitem.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "CartItem.price": %w`, err)}
		}
	}
	if v, ok := ciu.mutation.Image(); ok {
		if err := cartitem.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "CartItem.image": %w`, err)}
		}
	}
	if v, ok := ciu.mutation.Quantity(); ok {
		if err := cartitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "CartItem.quantity": %w`, err)}
		}
	}
	return nil
}

func (ciu *CartItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ciu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(cartitem.Table, cartitem.Columns, sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString))
	if ps := ciu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ciu.mutation.Name(); ok {
		_spec.SetField(cartitem.FieldName, field.TypeString, value)
	}
	if value, ok := ciu.mutation.Price(); ok {
		_spec.SetField(cartitem.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ciu.mutation.AddedPrice(); ok {
		_spec.AddField(cartitem.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ciu.mutation.Image(); ok {
		_spec.SetField(cartitem.FieldImage, field.TypeString, value)
	}
	if value, ok := ciu.mutation.Quantity(); ok {
		_spec.SetField(cartitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ciu.mutation.AddedQuantity(); ok {
		_spec.AddField(cartitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ciu.mutation.CreatedAt(); ok {
		_spec.SetField(cartitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ciu.mutation.UpdatedAt(); ok {
		_spec.SetField(cartitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if ciu.mutation.CartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.CartTable,
			Columns: []string{cartitem.CartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ciu.mutation.CartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.CartTable,
			Columns: []string{cartitem.CartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ciu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.ProductTable,
			Columns: []string{cartitem.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ciu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.ProductTable,
			Columns: []string{cartitem.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ciu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cartitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ciu.mutation.done = true
	return n, nil
}

// CartItemUpdateOne is the builder for updating a single CartItem entity.
type CartItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartItemMutation
}

// SetCartID sets the "cart_id" field.
func (ciuo *CartItemUpdateOne) SetCartID(s string) *CartItemUpdateOne {
	ciuo.mutation.SetCartID(s)
	return ciuo
}

// SetNillableCartID sets the "cart_id" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableCartID(s *string) *CartItemUpdateOne {
	if s != nil {
		ciuo.SetCartID(*s)
	}
	return ciuo
}

// ClearCartID clears the value of the "cart_id" field.
func (ciuo *CartItemUpdateOne) ClearCartID() *CartItemUpdateOne {
	ciuo.mutation.ClearCartID()
	return ciuo
}

// SetProductID sets the "product_id" field.
func (ciuo *CartItemUpdateOne) SetProductID(s string) *CartItemUpdateOne {
	ciuo.mutation.SetProductID(s)
	return ciuo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableProductID(s *string) *CartItemUpdateOne {
	if s != nil {
		ciuo.SetProductID(*s)
	}
	return ciuo
}

// ClearProductID clears the value of the "product_id" field.
func (ciuo *CartItemUpdateOne) ClearProductID() *CartItemUpdateOne {
	ciuo.mutation.ClearProductID()
	return ciuo
}

// SetName sets the "name" field.
func (ciuo *CartItemUpdateOne) SetName(s string) *CartItemUpdateOne {
	ciuo.mutation.SetName(s)
	return ciuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableName(s *string) *CartItemUpdateOne {
	if s != nil {
		ciuo.SetName(*s)
	}
	return ciuo
}

// SetPrice sets the "price" field.
func (ciuo *CartItemUpdateOne) SetPrice(f float64) *CartItemUpdateOne {
	ciuo.mutation.ResetPrice()
	ciuo.mutation.SetPrice(f)
	return ciuo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillablePrice(f *float64) *CartItemUpdateOne {
	if f != nil {
		ciuo.SetPrice(*f)
	}
	return ciuo
}

// AddPrice adds f to the "price" field.
func (ciuo *CartItemUpdateOne) AddPrice(f float64) *CartItemUpdateOne {
	ciuo.mutation.AddPrice(f)
	return ciuo
}

// SetImage sets the "image" field.
func (ciuo *CartItemUpdateOne) SetImage(s string) *CartItemUpdateOne {
	ciuo.mutation.SetImage(s)
	return ciuo
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableImage(s *string) *CartItemUpdateOne {
	if s != nil {
		ciuo.SetImage(*s)
	}
	return ciuo
}

// SetQuantity sets the "quantity" field.
func (ciuo *CartItemUpdateOne) SetQuantity(i int) *CartItemUpdateOne {
	ciuo.mutation.ResetQuantity()
	ciuo.mutation.SetQuantity(i)
	return ciuo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableQuantity(i *int) *CartItemUpdateOne {
	if i != nil {
		ciuo.SetQuantity(*i)
	}
	return ciuo
}

// AddQuantity adds i to the "quantity" field.
func (ciuo *CartItemUpdateOne) AddQuantity(i int) *CartItemUpdateOne {
	ciuo.mutation.AddQuantity(i)
	return ciuo
}

// SetCreatedAt sets the "created_at" field.
func (ciuo *CartItemUpdateOne) SetCreatedAt(t time.Time) *CartItemUpdateOne {
	ciuo.mutation.SetCreatedAt(t)
	return ciuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ciuo *CartItemUpdateOne) SetNillableCreatedAt(t *time.Time) *CartItemUpdateOne {
	if t != nil {
		ciuo.SetCreatedAt(*t)
	}
	return ciuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ciuo *CartItemUpdateOne) SetUpdatedAt(t time.Time) *CartItemUpdateOne {
	ciuo.mutation.SetUpdatedAt(t)
	return ciuo
}

// SetCart sets the "cart" edge to the Cart entity.
func (ciuo *CartItemUpdateOne) SetCart(c *Cart) *CartItemUpdateOne {
	return ciuo.SetCartID(c.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (ciuo *CartItemUpdateOne) SetProduct(p *Product) *CartItemUpdateOne {
	return ciuo.SetProductID(p.ID)
}

// Mutation returns the CartItemMutation object of the builder.
func (ciuo *CartItemUpdateOne) Mutation() *CartItemMutation {
	return ciuo.mutation
}

// ClearCart clears the "cart" edge to the Cart entity.
func (ciuo *CartItemUpdateOne) ClearCart() *CartItemUpdateOne {
	ciuo.mutation.ClearCart()
	return ciuo
}

// ClearProduct clears the "product" edge to the Product entity.
func (ciuo *CartItemUpdateOne) ClearProduct() *CartItemUpdateOne {
	ciuo.mutation.ClearProduct()
	return ciuo
}

// Where appends a list predicates to the CartItemUpdate builder.
func (ciuo *CartItemUpdateOne) Where(ps ...predicate.CartItem) *CartItemUpdateOne {
	ciuo.mutation.Where(ps...)
	return ciuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ciuo *CartItemUpdateOne) Select(field string, fields ...string) *CartItemUpdateOne {
	ciuo.fields = append([]string{field}, fields...)
	return ciuo
}

// Save executes the query and returns the updated CartItem entity.
func (ciuo *CartItemUpdateOne) Save(ctx context.Context) (*CartItem, error) {
	ciuo.defaults()
	return withHooks(ctx, ciuo.sqlSave, ciuo.mutation, ciuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ciuo *CartItemUpdateOne) SaveX(ctx context.Context) *CartItem {
	node, err := ciuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ciuo *CartItemUpdateOne) Exec(ctx context.Context) error {
	_, err := ciuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ciuo *CartItemUpdateOne) ExecX(ctx context.Context) {
	if err := ciuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ciuo *CartItemUpdateOne) defaults() {
	if _, ok := ciuo.mutation.UpdatedAt(); !ok {
		v := cartitem.UpdateDefaultUpdatedAt()
		ciuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ciuo *CartItemUpdateOne) check() error {
	if v, ok := ciuo.mutation.Name(); ok {
		if err := cartitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CartItem.name": %w`, err)}
		}
	}
	if v, ok := ciuo.mutation.Price(); ok {
		if err := cartitem.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "CartItem.price": %w`, err)}
		}
	}
	if v, ok := ciuo.mutation.Image(); ok {
		if err := cartitem.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "CartItem.image": %w`, err)}
		}
	}
	if v, ok := ciuo.mutation.Quantity(); ok {
		if err := cartitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "CartItem.quantity": %w`, err)}
		}
	}
	return nil
}

func (ciuo *CartItemUpdateOne) sqlSave(ctx context.Context) (_node *CartItem, err error) {
	if err := ciuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cartitem.Table, cartitem.Columns, sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeString))
	id, ok := ciuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CartItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ciuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cartitem.FieldID)
		for _, f := range fields {
			if !cartitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cartitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ciuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ciuo.mutation.Name(); ok {
		_spec.SetField(cartitem.FieldName, field.TypeString, value)
	}
	if value, ok := ciuo.mutation.Price(); ok {
		_spec.SetField(cartitem.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ciuo.mutation.AddedPrice(); ok {
		_spec.AddField(cartitem.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ciuo.mutation.Image(); ok {
		_spec.SetField(cartitem.FieldImage, field.TypeString, value)
	}
	if value, ok := ciuo.mutation.Quantity(); ok {
		_spec.SetField(cartitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ciuo.mutation.AddedQuantity(); ok {
		_spec.AddField(cartitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ciuo.mutation.CreatedAt(); ok {
		_spec.SetField(cartitem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ciuo.mutation.UpdatedAt(); ok {
		_spec.SetField(cartitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if ciuo.mutation.CartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.CartTable,
			Columns: []string{cartitem.CartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ciuo.mutation.CartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.CartTable,
			Columns: []string{cartitem.CartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cart.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ciuo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.ProductTable,
			Columns: []string{cartitem.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ciuo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.ProductTable,
			Columns: []string{cartitem.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CartItem{config: ciuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ciuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cartitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ciuo.mutation.done = true
	return _node, nil
}
